title: Ad Valorem Labs
description: Adding value to your life
url: https://advaloremlabs.github.io
baseurl: ""        # keep empty for an org site
theme: null        # turn off the default theme so this layout+CSS controls everything
